### ISSUE TITLE
Input to textarea for input and pattern fields

### ISSUE THREAD

**Issue by nisaac2fly** [nickethier/grokdebug#8]
Hello,

Any thoughts on changing the inputs to textarea's? I would find it easier to debug long lines of text. Right now I change it in the inspect element panel in chrome. 

Here is what it looks like if you change the inputs to textarea's:

![image](https://cloud.githubusercontent.com/assets/1559451/5530126/48917204-89d1-11e4-9f82-d8d3890289dd.png)

Thanks,

Nathan

**Comment by nickethier** [comment]
Closed by #9
